dataset:
  max_atoms: 20
  max_types: 100
  num_workers: 10
  primitive: true
  
diffusion:
  timesteps: 256
model:
  attn_head: 8
  cfg:
    guide_strength: 2.0
    p_cond: 0.2
    use: true
  cond_dim: 8
  decoder_layers: 8
  dropout: 0.0
  hidden_dim: 512
  loss:
    c: 0.3
    m: 0.3
    t: 0.3
training:
  batch_size: 128
  batch_size_eval: 10001
  check: 100
  epoch: 5000
  lr: 0.0001
use_gradscalar: true
use_schedule: false
wandb:
  project: compo
