dataset:
  max_atoms: 20
  max_types: 100
  num_workers: 100
  primitive: True

use_gradscalar: True
use_schedule: False

model:
  hidden_dim: 512
  latent_dim: 8
  decode_layers: 8
  neigh_layer: 8
  attn_head: 8
  dropout: 0.0
  neigh_num: 12

training:
  batch_size: 128
  lr: 0.0001
  epoch: 2000
  check: 10

wandb:
    project: compo
  
  